services:
  # BLA-BOT web service
  - type: web
    name: bla-bot
    env: python
    startCommand: python3 bla_bot.py
    buildCommand: pip install -r requirements.txt
    plan: free
    envVars:
      - key: ENV
        value: prod
      - key: PORT
        value: 8443
      - key: DEV_CHAT_ID
        sync: false
      - key: GROUP_CHAT_ID
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: RENDER_APP_URL
        sync: false
